# Generated by Django 5.1 on 2024-09-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
